admin:
  access_log_path: /envoy/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: http_alt
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:

              # Prometheus
              - match: { prefix: "/prometheus" }
                route: { cluster: prometheus }
              - match: { prefix: "/prometheus/*" }
                route: { cluster: prometheus }

              # Alert Manager
              - match: { prefix: "/alertmanager" }
                route: { cluster: alertmanager }
              - match: { prefix: "/alertmanager/*" }
                route: { cluster: alertmanager }

              # Push Gateway
              - match: { prefix: "/pushgateway" }
                route: { cluster: pushgateway }
              - match: { prefix: "/pushgateway/*" }
                route: { cluster: pushgateway }

              # BlackBox
              - match: { prefix: "/blackbox" }
                route: { cluster: blackbox }
              - match: { prefix: "/blackbox/*" }
                route: { cluster: blackbox }

              # Grafana
              - match: { prefix: "/grafana" }
                route: { cluster: grafana }
              - match: { prefix: "/grafana/*" }
                route: { cluster: grafana }

              # CAdvisor
              - match: { prefix: "/cadvisor" }
                route: { cluster: cadvisor }
              - match: { prefix: "/cadvisor/*" }
                route: { cluster: cadvisor }

              # DKRON - Redirect
              - match: { prefix: "/dkron/metrics" }
                redirect: { path_redirect: '/metrics', port_redirect: 8081 }
              - match: { prefix: "/dkron/metrics/*" }
                redirect: { path_redirect: '/metrics', port_redirect: 8081 }
              - match: { prefix: "/dkron" }
                redirect: { path_redirect: '/', port_redirect: 8081 }
              - match: { prefix: "/dkron/*" }
                redirect: { path_redirect: '/', port_redirect: 8081 }

              # ENVOY - Redirect
              - match: { prefix: "/envoy/metrics" }
                redirect: { path_redirect: '/stats/prometheus', port_redirect: 9901 }
              - match: { prefix: "/envoy/metrics/*" }
                redirect: { path_redirect: '/stats/prometheus', port_redirect: 9901 }
              - match: { prefix: "/envoy" }
                redirect: { path_redirect: '/', port_redirect: 9901 }
              - match: { prefix: "/envoy/*" }
                redirect: { path_redirect: '/', port_redirect: 9901 }

              # Node Exporter - Redirect
              - match: { prefix: "/node/metrics" }
                redirect: { path_redirect: '/metrics', port_redirect: 9100 }
              - match: { prefix: "/node/metrics/*" }
                redirect: { path_redirect: '/metrics', port_redirect: 9100 }
              - match: { prefix: "/node" }
                redirect: { path_redirect: '/', port_redirect: 9100 }
              - match: { prefix: "/node/*" }
                redirect: { path_redirect: '/', port_redirect: 9100 }

              # MarkDown Web Server (Default)
              - match: { prefix: "/" }
                route: { cluster: markweb }
              - match: { prefix: "/*" }
                route: { cluster: markweb }

          http_filters:
          - name: envoy.filters.http.router

  - name: dkron_alt
    address:
      socket_address: { address: 0.0.0.0, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:

              # DKRON
              - match: { prefix: "*" }
                route: { cluster: dkron }

          http_filters:
          - name: envoy.filters.http.router

  clusters:

    # Prometheus
    - name: prometheus
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: prometheus, port_value: 9090 }}

    # Alert Manager
    - name: alertmanager
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: alertmanager, port_value: 9093 }}

    # Push Gateway
    - name: pushgateway
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: pushgateway, port_value: 9091 }}

    # Black Box Exporter
    - name: blackbox
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: blackbox, port_value: 9115 }}

    # Grafana
    - name: grafana
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: grafana, port_value: 3000 }}

    # DKRON
    - name: dkron
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: dkron, port_value: 8080 }}

    # CAdvisor
    - name: cadvisor
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: cadvisor, port_value: 8080 }}

    # MarkDown Web Server
    - name: markweb
      connect_timeout: 1.0s
      type: logical_dns
      lb_policy: round_robin
      hosts:
        - { socket_address: { address: markweb, port_value: 3030 }}
